# Librerías de machine learning más usadas:

[librerías más usadas](../docs/01_librerías_ml.md)

# 1) Preprocesamiento y manipulación de datos

## NumPy

### 1. Creación de Arrays

In [1]:
import numpy as np

In [3]:
# Array desde lista
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# Matriz 2D
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Rango de valores
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
# Números igualmente espaciados
np.linspace(0, 1, 5)    # genera un array de 5 números igualmente espaciados entre 0 y 1 (incluyendo ambos extremos).

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Matrices especiales
np.zeros((3, 4))        # Matriz de ceros de 3 filas y 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 5))         # Matriz de unos de 2 filas y 5 columnas

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.eye(4)            # Matriz identidad de 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(2, 2)     # Matriz 2x2 con valores aleatorios entre 0 y 1

array([[0.94239785, 0.56427194],
       [0.62516219, 0.86861068]])

In [11]:
np.random.randn(2, 2)   # Matriz 2x2 con valores aleatorios de una distribución normal (media 0, desviación estándar 1)
# Se usa para simular datos con comportamiento normal (gaussiano).

array([[2.35303979, 0.54686764],
       [1.09585972, 1.41720339]])

In [12]:
np.random.randint(0, 10, (3, 3))  # Matriz 3x3 con enteros aleatorios entre 0 y 10

array([[1, 0, 9],
       [4, 3, 3],
       [5, 7, 5]])

In [13]:
np.random.randint(0, 10, 5)  # Array de 5 enteros aleatorios entre 0 y 10

array([8, 0, 6, 3, 1])

### 2. Inspección

In [14]:
a = np.array([[1,2,3],[4,5,6]])

In [15]:
a.shape       # Dimensiones del array (filas, columnas)

(2, 3)

In [16]:
a.ndim        # Número de dimensiones

2

In [17]:
a.size        # Número total de elementos

6

In [18]:
a.dtype       # Tipo de datos de los elementos

dtype('int64')

### 3. Operaciones Básicas

In [19]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

In [20]:
x + y       # Suma elemento a elemento

array([11, 22, 33])

In [21]:
x - y       # Resta elemento a elemento

array([ -9, -18, -27])

In [22]:
x * y       # Multiplicación elemento a elemento

array([10, 40, 90])

In [23]:
x / y       # División elemento a elemento

array([0.1, 0.1, 0.1])

In [24]:
x ** y      # Potenciación elemento a elemento

array([              1,         1048576, 205891132094649])

#### Operaciones escalares

In [25]:
x + 5

array([6, 7, 8])

In [26]:
y * 2

array([20, 40, 60])

### 4. Indexado y slicing

#### Arrays

In [27]:
a = np.array([10, 20, 30, 40, 50])

In [28]:
a[0]        # Primer elemento

np.int64(10)

In [29]:
a[-1]       # Último elemento

np.int64(50)

In [30]:
a[1:4]      # Elementos desde el índice 1 hasta el 3 (excluyendo el 4)

array([20, 30, 40])

In [31]:
a[::2]     # Elementos desde el inicio hasta el final, con paso 2

array([10, 30, 50])

#### Matrices

In [32]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [33]:
b[0, 2]      # Elemento en la primera fila, tercera columna

np.int64(3)

In [34]:
b[1, :]      # Todos los elementos de la segunda fila

array([4, 5, 6])

In [35]:
b[:, 1]      # Todos los elementos de la segunda columna

array([2, 5, 8])

### 5. Funciones estadísticas

In [36]:
data = np.array([1, 2, 3, 4, 5])

In [37]:
np.mean(data)      # Media

np.float64(3.0)

In [38]:
np.median(data)    # Mediana

np.float64(3.0)

In [39]:
np.std(data)       # Desviación estándar

np.float64(1.4142135623730951)

In [40]:
np.var(data)       # Varianza

np.float64(2.0)

In [41]:
np.min(data)       # Valor mínimo

np.int64(1)

In [42]:
np.max(data)       # Valor máximo

np.int64(5)

In [43]:
np.sum(data)       # Suma de todos los elementos

np.int64(15)

In [44]:
np.cumsum(data)    # Suma acumulativa

array([ 1,  3,  6, 10, 15])

### 6. Álgebra lineal

In [45]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
np.dot(A, B)   # Producto matricial de A y B

A @ B          # Producto matricial de A y B (otra sintaxis)

array([[19, 22],
       [43, 50]])

In [47]:
np.transpose(A)  # Transpuesta de A

array([[1, 3],
       [2, 4]])

In [48]:
np.linalg.inv(A)  # Inversa de A (si es invertible)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
np.linalg.det(A)  # Determinante de A

np.float64(-2.0000000000000004)

In [50]:
np.linalg.eig(A)  # Valores y vectores propios de A

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

### 7. Reshape y manipulación

In [53]:
a = np.arange(6)  # Array con valores del 0 al 5
a

array([0, 1, 2, 3, 4, 5])

In [54]:
a.reshape((2, 3))  # Cambia la forma a 2 filas y 3 columnas

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
a.reshape((-1, 2))  # Cambia la forma a 2 columnas, infiere el número de filas

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
a.flatten()  # Aplana el array a 1D

array([0, 1, 2, 3, 4, 5])

In [62]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [63]:
np.concatenate((x, y))  # Concatena x e y

array([1, 2, 3, 4, 5, 6])

### 8. Condiciones y máscaras

In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
arr > 3  # Devuelve un array booleano indicando dónde se cumple la condición

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
arr[arr > 3]  # Filtra los elementos que cumplen la condición

array([ 4,  5,  6,  7,  8,  9, 10])

In [72]:
np.where(arr > 3, 1, 0)  # Devuelve los índices donde se cumple la condición

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

## Pandas

In [3]:
import pandas as pd

### 1. Cargar datos

In [2]:
# Datos de ejemplo con 20 países (como en la tabla anterior)
data = [
    ["África", "República Centroafricana", "Bangui", "Francés, Sango", 5650957],
    ["África", "Gambia", "Banjul", "Inglés", 2422712],
    ["Asia", "Indonesia", "Yakarta", "Bahasa Indonesia", 281562465],
    ["América", "Guatemala", "Ciudad de Guatemala", "Español", 18255216],
    ["América", "Haití", "Puerto Príncipe", "Francés, Criollo haitiano", 11753943],
    ["Europa", "Francia", "París", "Francés", 68374591],
    ["Europa", "Bélgica", "Bruselas", "Francés, Neerlandés, Alemán", 11977634],
    ["América", "Canadá", "Ottawa", "Inglés, Francés", 38794813],
    ["África", "Camerún", "Yaundé", "Francés, Inglés", 30966105],
    ["África", "Costa de Marfil", "Yamusukro", "Francés", 29981758],
    ["África", "Madagascar", "Antananarivo", "Malgache, Francés", 29452714],
    ["África", "Senegal", "Dakar", "Francés", 18847519],
    ["África", "Burundi", "Buyumbura", "Kirundi, Francés", 13590102],
    ["Europa", "Suiza", "Berna", "Alemán, Francés, Italiano, Romanche", 8860574],
    ["África", "Congo (República del)", "Brazzaville", "Francés", 6097665],
    ["Oceanía", "Vanuatu", "Port Vila", "Bislama, Inglés, Francés", 318007],
    ["África", "Seychelles", "Victoria", "Criollo seychelense, Inglés, Francés", 98187],
    ["Europa", "Mónaco", "Mónaco", "Francés", 31813],
    ["América", "México", "Ciudad de México", "Español", 129875529],
    ["Asia", "Japón", "Tokio", "Japonés", 123753041]
]

# Crear DataFrame
df = pd.DataFrame(data, columns=["Continente", "País", "Capital", "Idioma(s) oficial(es)", "Población estimada (2024)"])

In [3]:
# Guardar como CSV
file_path = "./paises_extracto.csv"
df.to_csv(file_path, index=False)

In [4]:
# Cargar datos
# df = pd.read_csv(file_path)
df = pd.read_csv("./paises_extracto.csv")
df

Continente                      País              Capital  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
20    América                       NaN                  NaN   

                   Idioma(s) oficial(es)  Población estimada (2024)  
0                         Francés, Sango                  5650957.0  
1                                 Inglés                  2422712.0  
2                       Bahasa Indonesia                281562465.0  
3                                Español                 18255216.0  
4              Francés, Criollo haitiano                 11753943.0  
5                                Francés                 68374591.0  
6            Francés, Neerlandés, Alemán                 11977634.0  
7                        Inglés, Francés                 38794813.0  
8                        Francés, Inglés                 30966105.0  
9                                Francés                 29981758.0  
10                     Malgache, Francés                 29452714.0  
11                               Francés                 18847519.0  
12                      Kirundi, Francés                 13590102.0  
13   Alemán, Francés, Italiano, Romanche                  8860574.0  
14                               Francés                  6097665.0  
15              Bislama, Inglés, Francés                   318007.0  
16  Criollo seychelense, Inglés, Francés                    98187.0  
17                               Francés                    31813.0  
18                               Español                129875529.0  
19                               Japonés                123753041.0  
20                                   NaN                        NaN

### 2. Exploración

In [6]:
df.head(3)  # Primeras filas

Continente                      País  Capital Idioma(s) oficial(es)  \
0     África  República Centroafricana   Bangui        Francés, Sango   
1     África                    Gambia   Banjul                Inglés   
2       Asia                 Indonesia  Yakarta      Bahasa Indonesia   

   Población estimada (2024)  
0                    5650957  
1                    2422712  
2                  281562465

In [7]:
df.tail(6)  # Últimas filas

Continente                   País           Capital  \
14     África  Congo (República del)       Brazzaville   
15    Oceanía                Vanuatu         Port Vila   
16     África             Seychelles          Victoria   
17     Europa                 Mónaco            Mónaco   
18    América                 México  Ciudad de México   
19       Asia                  Japón             Tokio   

                   Idioma(s) oficial(es)  Población estimada (2024)  
14                               Francés                    6097665  
15              Bislama, Inglés, Francés                     318007  
16  Criollo seychelense, Inglés, Francés                      98187  
17                               Francés                      31813  
18                               Español                  129875529  
19                               Japonés                  123753041

In [8]:
df.info()  # Información del DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Continente                 20 non-null     object
 1   País                       20 non-null     object
 2   Capital                    20 non-null     object
 3   Idioma(s) oficial(es)      20 non-null     object
 4   Población estimada (2024)  20 non-null     int64 
dtypes: int64(1), object(4)
memory usage: 932.0+ bytes


In [9]:
df.describe()  # Estadísticas descriptivas

Población estimada (2024)
count               2.000000e+01
mean                4.153327e+07
std                 6.773533e+07
min                 3.181300e+04
25%                 5.985988e+06
50%                 1.592266e+07
75%                 3.292328e+07
max                 2.815625e+08

In [10]:
df.shape  # Dimensiones del DataFrame (filas, columnas)

(20, 5)

### 3. Selección de datos

In [11]:
df["Población estimada (2024)"] # Selección de una columna

0       5650957
1       2422712
2     281562465
3      18255216
4      11753943
5      68374591
6      11977634
7      38794813
8      30966105
9      29981758
10     29452714
11     18847519
12     13590102
13      8860574
14      6097665
15       318007
16        98187
17        31813
18    129875529
19    123753041
Name: Población estimada (2024), dtype: int64

In [12]:
df[["País", "Capital"]]  # Selección de múltiples columnas

País              Capital
0   República Centroafricana               Bangui
1                     Gambia               Banjul
2                  Indonesia              Yakarta
3                  Guatemala  Ciudad de Guatemala
4                      Haití      Puerto Príncipe
5                    Francia                París
6                    Bélgica             Bruselas
7                     Canadá               Ottawa
8                    Camerún               Yaundé
9            Costa de Marfil            Yamusukro
10                Madagascar         Antananarivo
11                   Senegal                Dakar
12                   Burundi            Buyumbura
13                     Suiza                Berna
14     Congo (República del)          Brazzaville
15                   Vanuatu            Port Vila
16                Seychelles             Victoria
17                    Mónaco               Mónaco
18                    México     Ciudad de México
19                     Japón                Tokio

In [14]:
df.loc[2, "Población estimada (2024)"]  # Valor específico (fila 2, columna "Población estimada (2024)")

np.int64(281562465)

In [15]:
df.iloc[2, 4]  # Valor específico usando índices (fila 2, columna 4)

np.int64(281562465)

### 4. Filtrado

In [16]:
df[df["Población estimada (2024)"] > 50000000]  # Filtrar países con población mayor a 50 millones

Continente       País           Capital Idioma(s) oficial(es)  \
2        Asia  Indonesia           Yakarta      Bahasa Indonesia   
5      Europa    Francia             París               Francés   
18    América     México  Ciudad de México               Español   
19       Asia      Japón             Tokio               Japonés   

    Población estimada (2024)  
2                   281562465  
5                    68374591  
18                  129875529  
19                  123753041

In [ ]:
df.query("`Idioma(s) oficial(es)`.str.contains('Francés') and `Población estimada (2024)` < 1000000")   # Filtrar con múltiples condiciones


Continente        País    Capital                 Idioma(s) oficial(es)  \
15    Oceanía     Vanuatu  Port Vila              Bislama, Inglés, Francés   
16     África  Seychelles   Victoria  Criollo seychelense, Inglés, Francés   
17     Europa      Mónaco     Mónaco                               Francés   

    Población estimada (2024)  
15                     318007  
16                      98187  
17                      31813

### 5. Ordenar y ranking

In [25]:
df.sort_values(by="Población estimada (2024)", ascending=False)  # Ordenar por población descendente

Continente                      País              Capital  \
2        Asia                 Indonesia              Yakarta   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
5      Europa                   Francia                París   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
3     América                 Guatemala  Ciudad de Guatemala   
12     África                   Burundi            Buyumbura   
6      Europa                   Bélgica             Bruselas   
4     América                     Haití      Puerto Príncipe   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   

                   Idioma(s) oficial(es)  Población estimada (2024)  
2                       Bahasa Indonesia                  281562465  
18                               Español                  129875529  
19                               Japonés                  123753041  
5                                Francés                   68374591  
7                        Inglés, Francés                   38794813  
8                        Francés, Inglés                   30966105  
9                                Francés                   29981758  
10                     Malgache, Francés                   29452714  
11                               Francés                   18847519  
3                                Español                   18255216  
12                      Kirundi, Francés                   13590102  
6            Francés, Neerlandés, Alemán                   11977634  
4              Francés, Criollo haitiano                   11753943  
13   Alemán, Francés, Italiano, Romanche                    8860574  
14                               Francés                    6097665  
0                         Francés, Sango                    5650957  
1                                 Inglés                    2422712  
15              Bislama, Inglés, Francés                     318007  
16  Criollo seychelense, Inglés, Francés                      98187  
17                               Francés                      31813

In [27]:
df.rank()  # Ranking de todas las columnas numéricas

Continente  País  Capital  Idioma(s) oficial(es)  \
0         16.0  16.0      2.0                   15.0   
1         16.0   8.0      3.0                   16.0   
2          5.5  11.0     18.0                    2.0   
3          2.5   9.0      8.0                    5.5   
4          2.5  10.0     15.0                   12.0   
5          8.5   7.0     13.0                    9.0   
6          8.5   2.0      6.0                   14.0   
7          2.5   4.0     12.0                   17.0   
8         16.0   3.0     20.0                   13.0   
9         16.0   6.0     19.0                    9.0   
10        16.0  13.0      1.0                   20.0   
11        16.0  17.0     10.0                    9.0   
12        16.0   1.0      7.0                   19.0   
13         8.5  19.0      4.0                    1.0   
14        16.0   5.0      5.0                    9.0   
15        11.0  20.0     14.0                    3.0   
16        16.0  18.0     17.0                    4.0   
17         8.5  15.0     11.0                    9.0   
18         2.5  14.0      9.0                    5.5   
19         5.5  12.0     16.0                   18.0   

    Población estimada (2024)  
0                         5.0  
1                         4.0  
2                        20.0  
3                        11.0  
4                         8.0  
5                        17.0  
6                         9.0  
7                        16.0  
8                        15.0  
9                        14.0  
10                       13.0  
11                       12.0  
12                       10.0  
13                        7.0  
14                        6.0  
15                        3.0  
16                        2.0  
17                        1.0  
18                       19.0  
19                       18.0

### 6. Transformación

In [7]:
df.rename(columns={"Población estimada (2024)": "Población_2024"}, inplace=True)  # Renombrar columna
df.head()

Continente                      País              Capital  \
0     África  República Centroafricana               Bangui   
1     África                    Gambia               Banjul   
2       Asia                 Indonesia              Yakarta   
3    América                 Guatemala  Ciudad de Guatemala   
4    América                     Haití      Puerto Príncipe   

       Idioma(s) oficial(es)  Población_2024  
0             Francés, Sango       5650957.0  
1                     Inglés       2422712.0  
2           Bahasa Indonesia     281562465.0  
3                    Español      18255216.0  
4  Francés, Criollo haitiano      11753943.0

In [13]:
df2 = df.drop(
    columns=["Continente"],
    axis=1
)  # Eliminar columna

df2.head()

País              Capital      Idioma(s) oficial(es)  \
0  República Centroafricana               Bangui             Francés, Sango   
1                    Gambia               Banjul                     Inglés   
2                 Indonesia              Yakarta           Bahasa Indonesia   
3                 Guatemala  Ciudad de Guatemala                    Español   
4                     Haití      Puerto Príncipe  Francés, Criollo haitiano   

   Población_2024  
0       5650957.0  
1       2422712.0  
2     281562465.0  
3      18255216.0  
4      11753943.0

In [56]:
df.dropna() # Eliminar filas con valores nulos

Continente                      País              Capital  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   

                   Idioma(s) oficial(es)  Población_2024  
0                         Francés, Sango       5650957.0  
1                                 Inglés       2422712.0  
2                       Bahasa Indonesia     281562465.0  
3                                Español      18255216.0  
4              Francés, Criollo haitiano      11753943.0  
5                                Francés      68374591.0  
6            Francés, Neerlandés, Alemán      11977634.0  
7                        Inglés, Francés      38794813.0  
8                        Francés, Inglés      30966105.0  
9                                Francés      29981758.0  
10                     Malgache, Francés      29452714.0  
11                               Francés      18847519.0  
12                      Kirundi, Francés      13590102.0  
13   Alemán, Francés, Italiano, Romanche       8860574.0  
14                               Francés       6097665.0  
15              Bislama, Inglés, Francés        318007.0  
16  Criollo seychelense, Inglés, Francés         98187.0  
17                               Francés         31813.0  
18                               Español     129875529.0  
19                               Japonés     123753041.0

In [57]:
df.fillna("desconocido") # Rellenar valores nulos con "desconocido"

Continente                      País              Capital  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
20    América               desconocido          desconocido   

                   Idioma(s) oficial(es) Población_2024  
0                         Francés, Sango      5650957.0  
1                                 Inglés      2422712.0  
2                       Bahasa Indonesia    281562465.0  
3                                Español     18255216.0  
4              Francés, Criollo haitiano     11753943.0  
5                                Francés     68374591.0  
6            Francés, Neerlandés, Alemán     11977634.0  
7                        Inglés, Francés     38794813.0  
8                        Francés, Inglés     30966105.0  
9                                Francés     29981758.0  
10                     Malgache, Francés     29452714.0  
11                               Francés     18847519.0  
12                      Kirundi, Francés     13590102.0  
13   Alemán, Francés, Italiano, Romanche      8860574.0  
14                               Francés      6097665.0  
15              Bislama, Inglés, Francés       318007.0  
16  Criollo seychelense, Inglés, Francés        98187.0  
17                               Francés        31813.0  
18                               Español    129875529.0  
19                               Japonés    123753041.0  
20                           desconocido    desconocido

In [60]:
df["Población_2025"] = df["Población_2024"].apply(lambda x: x * 1.01)  # Añadir nueva columna con población estimada para 2025 (1% más)
df

Continente                      País              Capital  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
20    América                       NaN                  NaN   

                   Idioma(s) oficial(es)  Población_2024  Población_2025  
0                         Francés, Sango       5650957.0    5.707467e+06  
1                                 Inglés       2422712.0    2.446939e+06  
2                       Bahasa Indonesia     281562465.0    2.843781e+08  
3                                Español      18255216.0    1.843777e+07  
4              Francés, Criollo haitiano      11753943.0    1.187148e+07  
5                                Francés      68374591.0    6.905834e+07  
6            Francés, Neerlandés, Alemán      11977634.0    1.209741e+07  
7                        Inglés, Francés      38794813.0    3.918276e+07  
8                        Francés, Inglés      30966105.0    3.127577e+07  
9                                Francés      29981758.0    3.028158e+07  
10                     Malgache, Francés      29452714.0    2.974724e+07  
11                               Francés      18847519.0    1.903599e+07  
12                      Kirundi, Francés      13590102.0    1.372600e+07  
13   Alemán, Francés, Italiano, Romanche       8860574.0    8.949180e+06  
14                               Francés       6097665.0    6.158642e+06  
15              Bislama, Inglés, Francés        318007.0    3.211871e+05  
16  Criollo seychelense, Inglés, Francés         98187.0    9.916887e+04  
17                               Francés         31813.0    3.213113e+04  
18                               Español     129875529.0    1.311743e+08  
19                               Japonés     123753041.0    1.249906e+08  
20                                   NaN             NaN             NaN

### 7. Agrupar y resumir

In [6]:
df.groupby("Continente")["Población estimada (2024)"].sum()  # Sumar población por continente

Continente
América    198679501.0
Asia       405315506.0
Europa      89244612.0
Oceanía       318007.0
África     137107719.0
Name: Población estimada (2024), dtype: float64

In [8]:
df.groupby(["Continente", "Idioma(s) oficial(es)"]).size()  # Contar países por continente e idioma oficial

Continente  Idioma(s) oficial(es)               
América     Español                                 2
            Francés, Criollo haitiano               1
            Inglés, Francés                         1
Asia        Bahasa Indonesia                        1
            Japonés                                 1
Europa      Alemán, Francés, Italiano, Romanche     1
            Francés                                 2
            Francés, Neerlandés, Alemán             1
Oceanía     Bislama, Inglés, Francés                1
África      Criollo seychelense, Inglés, Francés    1
            Francés                                 3
            Francés, Inglés                         1
            Francés, Sango                          1
            Inglés                                  1
            Kirundi, Francés                        1
            Malgache, Francés                       1
dtype: int64

### 8. Estadísticas rápidas

In [9]:
df["Continente"].value_counts()  # Contar número de países por continente

Continente
África     9
América    5
Europa     4
Asia       2
Oceanía    1
Name: count, dtype: int64

In [10]:
df["Idioma(s) oficial(es)"].unique()  # Listar idiomas oficiales únicos

array(['Francés, Sango', 'Inglés', 'Bahasa Indonesia', 'Español',
       'Francés, Criollo haitiano', 'Francés',
       'Francés, Neerlandés, Alemán', 'Inglés, Francés',
       'Francés, Inglés', 'Malgache, Francés', 'Kirundi, Francés',
       'Alemán, Francés, Italiano, Romanche', 'Bislama, Inglés, Francés',
       'Criollo seychelense, Inglés, Francés', 'Japonés', nan],
      dtype=object)

In [11]:
df["Idioma(s) oficial(es)"].nunique()  # Contar idiomas oficiales únicos

15

### 9. Uniones y Merge

In [14]:
pd.concat([df, df2], axis=1)  # Concatenar df y df2 horizontalmente

Continente                      País              Capital  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
20    América                       NaN                  NaN   

                   Idioma(s) oficial(es)  Población_2024  \
0                         Francés, Sango       5650957.0   
1                                 Inglés       2422712.0   
2                       Bahasa Indonesia     281562465.0   
3                                Español      18255216.0   
4              Francés, Criollo haitiano      11753943.0   
5                                Francés      68374591.0   
6            Francés, Neerlandés, Alemán      11977634.0   
7                        Inglés, Francés      38794813.0   
8                        Francés, Inglés      30966105.0   
9                                Francés      29981758.0   
10                     Malgache, Francés      29452714.0   
11                               Francés      18847519.0   
12                      Kirundi, Francés      13590102.0   
13   Alemán, Francés, Italiano, Romanche       8860574.0   
14                               Francés       6097665.0   
15              Bislama, Inglés, Francés        318007.0   
16  Criollo seychelense, Inglés, Francés         98187.0   
17                               Francés         31813.0   
18                               Español     129875529.0   
19                               Japonés     123753041.0   
20                                   NaN             NaN   

                        País              Capital  \
0   República Centroafricana               Bangui   
1                     Gambia               Banjul   
2                  Indonesia              Yakarta   
3                  Guatemala  Ciudad de Guatemala   
4                      Haití      Puerto Príncipe   
5                    Francia                París   
6                    Bélgica             Bruselas   
7                     Canadá               Ottawa   
8                    Camerún               Yaundé   
9            Costa de Marfil            Yamusukro   
10                Madagascar         Antananarivo   
11                   Senegal                Dakar   
12                   Burundi            Buyumbura   
13                     Suiza                Berna   
14     Congo (República del)          Brazzaville   
15                   Vanuatu            Port Vila   
16                Seychelles             Victoria   
17                    Mónaco               Mónaco   
18                    México     Ciudad de México   
19                     Japón                Tokio   
20                       NaN                  NaN   

                   Idioma(s) oficial(es)  Población_2024  
0                         Francés, Sango       

In [15]:
df.merge(df2, left_on="País", right_on="País", how="inner")  # Merge df y df2 por la columna "País"

Continente                      País            Capital_x  \
0      África  República Centroafricana               Bangui   
1      África                    Gambia               Banjul   
2        Asia                 Indonesia              Yakarta   
3     América                 Guatemala  Ciudad de Guatemala   
4     América                     Haití      Puerto Príncipe   
5      Europa                   Francia                París   
6      Europa                   Bélgica             Bruselas   
7     América                    Canadá               Ottawa   
8      África                   Camerún               Yaundé   
9      África           Costa de Marfil            Yamusukro   
10     África                Madagascar         Antananarivo   
11     África                   Senegal                Dakar   
12     África                   Burundi            Buyumbura   
13     Europa                     Suiza                Berna   
14     África     Congo (República del)          Brazzaville   
15    Oceanía                   Vanuatu            Port Vila   
16     África                Seychelles             Victoria   
17     Europa                    Mónaco               Mónaco   
18    América                    México     Ciudad de México   
19       Asia                     Japón                Tokio   
20    América                       NaN                  NaN   

                 Idioma(s) oficial(es)_x  Población_2024_x  \
0                         Francés, Sango         5650957.0   
1                                 Inglés         2422712.0   
2                       Bahasa Indonesia       281562465.0   
3                                Español        18255216.0   
4              Francés, Criollo haitiano        11753943.0   
5                                Francés        68374591.0   
6            Francés, Neerlandés, Alemán        11977634.0   
7                        Inglés, Francés        38794813.0   
8                        Francés, Inglés        30966105.0   
9                                Francés        29981758.0   
10                     Malgache, Francés        29452714.0   
11                               Francés        18847519.0   
12                      Kirundi, Francés        13590102.0   
13   Alemán, Francés, Italiano, Romanche         8860574.0   
14                               Francés         6097665.0   
15              Bislama, Inglés, Francés          318007.0   
16  Criollo seychelense, Inglés, Francés           98187.0   
17                               Francés           31813.0   
18                               Español       129875529.0   
19                               Japonés       123753041.0   
20                                   NaN               NaN   

              Capital_y               Idioma(s) oficial(es)_y  \
0                Bangui                        Francés, Sango   
1                Banjul                                Inglés   
2               Yakarta                      Bahasa Indonesia   
3   Ciudad de Guatemala                               Español   
4       Puerto Príncipe             Francés, Criollo haitiano   
5                 París                               Francés   
6              Bruselas           Francés, Neerlandés, Alemán   
7                Ottawa                       Inglés, Francés   
8                Yaundé                       Francés, Inglés   
9             Yamusukro                               Francés   
10         Antananarivo                     Malgache, Francés   
11                Dakar                               Francés   
12            Buyumbura                      Kirundi, Francés   
13                Berna   Alemán, Francés, Italiano, Romanche   
14          Brazzaville                               Francés   
15            Port Vila              Bislama, Inglés, Francés   
16             Victoria  Criollo seychelense, Inglés, Francés   
17               Mónaco                               Franc

### 10. Índices

In [16]:
df.set_index("País")  # Establecer la columna "País" como índice

Continente              Capital  \
País                                                       
República Centroafricana     África               Bangui   
Gambia                       África               Banjul   
Indonesia                      Asia              Yakarta   
Guatemala                   América  Ciudad de Guatemala   
Haití                       América      Puerto Príncipe   
Francia                      Europa                París   
Bélgica                      Europa             Bruselas   
Canadá                      América               Ottawa   
Camerún                      África               Yaundé   
Costa de Marfil              África            Yamusukro   
Madagascar                   África         Antananarivo   
Senegal                      África                Dakar   
Burundi                      África            Buyumbura   
Suiza                        Europa                Berna   
Congo (República del)        África          Brazzaville   
Vanuatu                     Oceanía            Port Vila   
Seychelles                   África             Victoria   
Mónaco                       Europa               Mónaco   
México                      América     Ciudad de México   
Japón                          Asia                Tokio   
NaN                         América                  NaN   

                                         Idioma(s) oficial(es)  Población_2024  
País                                                                            
República Centroafricana                        Francés, Sango       5650957.0  
Gambia                                                  Inglés       2422712.0  
Indonesia                                     Bahasa Indonesia     281562465.0  
Guatemala                                              Español      18255216.0  
Haití                                Francés, Criollo haitiano      11753943.0  
Francia                                                Francés      68374591.0  
Bélgica                            Francés, Neerlandés, Alemán      11977634.0  
Canadá                                         Inglés, Francés      38794813.0  
Camerún                                        Francés, Inglés      30966105.0  
Costa de Marfil                                        Francés      29981758.0  
Madagascar                                   Malgache, Francés      29452714.0  
Senegal                                                Francés      18847519.0  
Burundi                                       Kirundi, Francés      13590102.0  
Suiza                      Alemán, Francés, Italiano, Romanche       8860574.0  
Congo (República del)                                  Francés       6097665.0  
Vanuatu                               Bislama, Inglés, Francés        318007.0  
Seychelles                Criollo seychelense, Inglés, Francés         98187.0  
Mónaco                                                 Francés         31813.0  
México                                                 Español     129875529.0  
Japón                                                  Japonés     123753041.0  
NaN                                                        NaN             NaN

In [17]:
df.reset_index()  # Restablecer el índice al valor predeterminado (0, 1, 2, ...)

index Continente                      País              Capital  \
0       0     África  República Centroafricana               Bangui   
1       1     África                    Gambia               Banjul   
2       2       Asia                 Indonesia              Yakarta   
3       3    América                 Guatemala  Ciudad de Guatemala   
4       4    América                     Haití      Puerto Príncipe   
5       5     Europa                   Francia                París   
6       6     Europa                   Bélgica             Bruselas   
7       7    América                    Canadá               Ottawa   
8       8     África                   Camerún               Yaundé   
9       9     África           Costa de Marfil            Yamusukro   
10     10     África                Madagascar         Antananarivo   
11     11     África                   Senegal                Dakar   
12     12     África                   Burundi            Buyumbura   
13     13     Europa                     Suiza                Berna   
14     14     África     Congo (República del)          Brazzaville   
15     15    Oceanía                   Vanuatu            Port Vila   
16     16     África                Seychelles             Victoria   
17     17     Europa                    Mónaco               Mónaco   
18     18    América                    México     Ciudad de México   
19     19       Asia                     Japón                Tokio   
20     20    América                       NaN                  NaN   

                   Idioma(s) oficial(es)  Población_2024  
0                         Francés, Sango       5650957.0  
1                                 Inglés       2422712.0  
2                       Bahasa Indonesia     281562465.0  
3                                Español      18255216.0  
4              Francés, Criollo haitiano      11753943.0  
5                                Francés      68374591.0  
6            Francés, Neerlandés, Alemán      11977634.0  
7                        Inglés, Francés      38794813.0  
8                        Francés, Inglés      30966105.0  
9                                Francés      29981758.0  
10                     Malgache, Francés      29452714.0  
11                               Francés      18847519.0  
12                      Kirundi, Francés      13590102.0  
13   Alemán, Francés, Italiano, Romanche       8860574.0  
14                               Francés       6097665.0  
15              Bislama, Inglés, Francés        318007.0  
16  Criollo seychelense, Inglés, Francés         98187.0  
17                               Francés         31813.0  
18                               Español     129875529.0  
19                               Japonés     123753041.0  
20                                   NaN             NaN

### 11. Pivot & Reshape

In [18]:
df.pivot(index="País", columns="Continente", values="Población_2024")  # Pivotar el DataFrame

Continente                    América         Asia      Europa   Oceanía  \
País                                                                       
NaN                               NaN          NaN         NaN       NaN   
Burundi                           NaN          NaN         NaN       NaN   
Bélgica                           NaN          NaN  11977634.0       NaN   
Camerún                           NaN          NaN         NaN       NaN   
Canadá                     38794813.0          NaN         NaN       NaN   
Congo (República del)             NaN          NaN         NaN       NaN   
Costa de Marfil                   NaN          NaN         NaN       NaN   
Francia                           NaN          NaN  68374591.0       NaN   
Gambia                            NaN          NaN         NaN       NaN   
Guatemala                  18255216.0          NaN         NaN       NaN   
Haití                      11753943.0          NaN         NaN       NaN   
Indonesia                         NaN  281562465.0         NaN       NaN   
Japón                             NaN  123753041.0         NaN       NaN   
Madagascar                        NaN          NaN         NaN       NaN   
México                    129875529.0          NaN         NaN       NaN   
Mónaco                            NaN          NaN     31813.0       NaN   
República Centroafricana          NaN          NaN         NaN       NaN   
Senegal                           NaN          NaN         NaN       NaN   
Seychelles                        NaN          NaN         NaN       NaN   
Suiza                             NaN          NaN   8860574.0       NaN   
Vanuatu                           NaN          NaN         NaN  318007.0   

Continente                    África  
País                                  
NaN                              NaN  
Burundi                   13590102.0  
Bélgica                          NaN  
Camerún                   30966105.0  
Canadá                           NaN  
Congo (República del)      6097665.0  
Costa de Marfil           29981758.0  
Francia                          NaN  
Gambia                     2422712.0  
Guatemala                        NaN  
Haití                            NaN  
Indonesia                        NaN  
Japón                            NaN  
Madagascar                29452714.0  
México                           NaN  
Mónaco                           NaN  
República Centroafricana   5650957.0  
Senegal                   18847519.0  
Seychelles                   98187.0  
Suiza                            NaN  
Vanuatu                          NaN

In [24]:
df.melt(id_vars=["País"]) # Deshacer el pivot (melt)

País        variable        value
0   República Centroafricana      Continente       África
1                     Gambia      Continente       África
2                  Indonesia      Continente         Asia
3                  Guatemala      Continente      América
4                      Haití      Continente      América
..                       ...             ...          ...
79                Seychelles  Población_2024      98187.0
80                    Mónaco  Población_2024      31813.0
81                    México  Población_2024  129875529.0
82                     Japón  Población_2024  123753041.0
83                       NaN  Población_2024          NaN

[84 rows x 3 columns]

## Scikit-learn