# Librerías de machine learning más usadas:

[librerías más usadas](../docs/01_librerías_ml.md)

# 1) Preprocesamiento y manipulación de datos

## NumPy

### 1. Creación de Arrays

In [1]:
import numpy as np

In [3]:
# Array desde lista
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# Matriz 2D
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Rango de valores
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
# Números igualmente espaciados
np.linspace(0, 1, 5)    # genera un array de 5 números igualmente espaciados entre 0 y 1 (incluyendo ambos extremos).

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Matrices especiales
np.zeros((3, 4))        # Matriz de ceros de 3 filas y 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 5))         # Matriz de unos de 2 filas y 5 columnas

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.eye(4)            # Matriz identidad de 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(2, 2)     # Matriz 2x2 con valores aleatorios entre 0 y 1

array([[0.94239785, 0.56427194],
       [0.62516219, 0.86861068]])

In [11]:
np.random.randn(2, 2)   # Matriz 2x2 con valores aleatorios de una distribución normal (media 0, desviación estándar 1)
# Se usa para simular datos con comportamiento normal (gaussiano).

array([[2.35303979, 0.54686764],
       [1.09585972, 1.41720339]])

In [12]:
np.random.randint(0, 10, (3, 3))  # Matriz 3x3 con enteros aleatorios entre 0 y 10

array([[1, 0, 9],
       [4, 3, 3],
       [5, 7, 5]])

In [13]:
np.random.randint(0, 10, 5)  # Array de 5 enteros aleatorios entre 0 y 10

array([8, 0, 6, 3, 1])

### 2. Inspección

In [14]:
a = np.array([[1,2,3],[4,5,6]])

In [15]:
a.shape       # Dimensiones del array (filas, columnas)

(2, 3)

In [16]:
a.ndim        # Número de dimensiones

2

In [17]:
a.size        # Número total de elementos

6

In [18]:
a.dtype       # Tipo de datos de los elementos

dtype('int64')

### 3. Operaciones Básicas

In [19]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

In [20]:
x + y       # Suma elemento a elemento

array([11, 22, 33])

In [21]:
x - y       # Resta elemento a elemento

array([ -9, -18, -27])

In [22]:
x * y       # Multiplicación elemento a elemento

array([10, 40, 90])

In [23]:
x / y       # División elemento a elemento

array([0.1, 0.1, 0.1])

In [24]:
x ** y      # Potenciación elemento a elemento

array([              1,         1048576, 205891132094649])

#### Operaciones escalares

In [25]:
x + 5

array([6, 7, 8])

In [26]:
y * 2

array([20, 40, 60])

### 4. Indexado y slicing

#### Arrays

In [27]:
a = np.array([10, 20, 30, 40, 50])

In [28]:
a[0]        # Primer elemento

np.int64(10)

In [29]:
a[-1]       # Último elemento

np.int64(50)

In [30]:
a[1:4]      # Elementos desde el índice 1 hasta el 3 (excluyendo el 4)

array([20, 30, 40])

In [31]:
a[::2]     # Elementos desde el inicio hasta el final, con paso 2

array([10, 30, 50])

#### Matrices

In [32]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [33]:
b[0, 2]      # Elemento en la primera fila, tercera columna

np.int64(3)

In [34]:
b[1, :]      # Todos los elementos de la segunda fila

array([4, 5, 6])

In [35]:
b[:, 1]      # Todos los elementos de la segunda columna

array([2, 5, 8])

### 5. Funciones estadísticas

In [36]:
data = np.array([1, 2, 3, 4, 5])

In [37]:
np.mean(data)      # Media

np.float64(3.0)

In [38]:
np.median(data)    # Mediana

np.float64(3.0)

In [39]:
np.std(data)       # Desviación estándar

np.float64(1.4142135623730951)

In [40]:
np.var(data)       # Varianza

np.float64(2.0)

In [41]:
np.min(data)       # Valor mínimo

np.int64(1)

In [42]:
np.max(data)       # Valor máximo

np.int64(5)

In [43]:
np.sum(data)       # Suma de todos los elementos

np.int64(15)

In [44]:
np.cumsum(data)    # Suma acumulativa

array([ 1,  3,  6, 10, 15])

### 6. Álgebra lineal

In [45]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
np.dot(A, B)   # Producto matricial de A y B

A @ B          # Producto matricial de A y B (otra sintaxis)

array([[19, 22],
       [43, 50]])

In [47]:
np.transpose(A)  # Transpuesta de A

array([[1, 3],
       [2, 4]])

In [48]:
np.linalg.inv(A)  # Inversa de A (si es invertible)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
np.linalg.det(A)  # Determinante de A

np.float64(-2.0000000000000004)

In [50]:
np.linalg.eig(A)  # Valores y vectores propios de A

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

### 7. Reshape y manipulación

In [53]:
a = np.arange(6)  # Array con valores del 0 al 5
a

array([0, 1, 2, 3, 4, 5])

In [54]:
a.reshape((2, 3))  # Cambia la forma a 2 filas y 3 columnas

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
a.reshape((-1, 2))  # Cambia la forma a 2 columnas, infiere el número de filas

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
a.flatten()  # Aplana el array a 1D

array([0, 1, 2, 3, 4, 5])

In [62]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [63]:
np.concatenate((x, y))  # Concatena x e y

array([1, 2, 3, 4, 5, 6])

### 8. Condiciones y máscaras

In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
arr > 3  # Devuelve un array booleano indicando dónde se cumple la condición

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
arr[arr > 3]  # Filtra los elementos que cumplen la condición

array([ 4,  5,  6,  7,  8,  9, 10])

In [72]:
np.where(arr > 3, 1, 0)  # Devuelve los índices donde se cumple la condición

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

## Pandas

## Scikit-learn